// lib/living-koral-edition/types.ts
// KORA-WP-115 — KORAL Edition (Portrait folded into Edition).
//
// Data contracts for the persisted analytics.living_koral_edition record
// — distinct from lib/living-koral-transformation-ledger/types.ts (the
// Ledger row this WP only ever REFERENCES, never duplicates) and from
// lib/living-koral-company-view/types.ts (WP-114's own current-state DTO,
// unmodified by this WP).
//
// AN EDITION IS a frozen reference (one Ledger row + engine version),
// Company-named, immutable once created — never current mutable state,
// never a transformation, never a Review, never a Mark, never a public
// artifact, never an exported asset (pre-check 174 §4, this WP's own §1).
//
// Deliberately absent (KORA-WP-116+'s own scope): any review/verdict/
// assessment field, any publication/visibility/public-slug field, any
// export/download-status field, any Mark/image/geometry field of any
// kind.

/** One immutable, persisted analytics.living_koral_edition row — domain truth, never handed to a component directly. */
export interface LivingKoralEditionRecord {
  readonly id: string;
  readonly tenantId: string;
  readonly name: string;
  readonly ledgerId: string;
  readonly category: 'Emergence' | 'Disappearance' | 'Strengthening' | 'Weakening' | 'Consolidation' | 'Reorientation' | 'Stabilization';
  readonly affectedDomain: 'initiative';
  readonly taxonomyConfigVersion: string;
  readonly morphogenesisEngineVersion: string;
  readonly resultingStateRevision: number;
  readonly occurredAt: string;
  readonly recognizedAt: string;
  /** Frozen at creation (Founder adjudication #1) — never re-resolved live. `null` when no source was resolvable. */
  readonly sourceLabel: string | null;
  readonly actorRole: 'COMPANY_ADMIN';
  readonly actorId: string;
  readonly createdAt: string;
}

export interface CreateLivingKoralEditionParams {
  readonly tenantId: string;
  readonly name: string;
  /** Caller-supplied, stable across retries of the SAME logical request (KORA-WP-011's own contract — never generated by this module). */
  readonly idempotencyKey: string;
}

export type CreateLivingKoralEditionResult =
  | { readonly kind: 'created'; readonly edition: LivingKoralEditionRecord }
  | { readonly kind: 'replayed'; readonly edition: LivingKoralEditionRecord }
  | { readonly kind: 'conflict' }
  | { readonly kind: 'in_progress' }
  | { readonly kind: 'no_recognized_transformation' }
  | { readonly kind: 'invalid_name' };
