// lib/ingestion-hardening/company-ingest-service.ts
// KORA-WP-028 — Ingestion Hardening — Sync Path + Retry Contract.
//
// Adds the first real, synchronous, Company-scoped server-side persistence
// step for the `app/company/data/upload` domain (KORA-WP-001's own Runtime
// Evidence Spike, `105`, confirmed that page has zero server-side write
// today). Consumes KORA-WP-011's async/idempotency contract unmodified —
// no second idempotency abstraction, no dedup mechanism of its own.
//
// R-1 EVIDENCE (`105`, closed): CSV parsing is linear, 665ms/23MB at 100,000
// rows, zero server load (client parse). The still-open question R-1 named
// — "the real, persisted, server-side ingestion write path... does not
// exist yet... its performance is an entirely separate, still-open
// question" — is exactly what this module answers: MAX_ROWS below is set
// to R-1's own tested bound (100,000), never invented past it. R-1's own
// scope note: only the CSV path was load-tested; XLSX support here reuses
// the same, already-proven `lib/data-intake/excel-parser.ts` module used
// elsewhere in this repo, but its throughput at this exact volume was not
// independently re-measured by R-1 — disclosed, not silently assumed.
//
// SCOPE BOUNDARY (registry's own "Out of Scope: durable queue runtime
// (KORA-WP-065)"): synchronous only — one HTTP request, one parse, one
// write. No queue, no worker, no background job of any kind.
//
// DATA/MIGRATION IMPACT ON DOMAIN TABLES: NONE. Writes exactly one
// `analytics.source_batch` row per successful ingest — the existing table,
// unmodified shape, `service_role`'s own pre-existing grants (confirmed by
// inspection, no grant change needed). Never writes `personal.
// uploaded_record` (KORA_ADMIN-exclusive, FORCE RLS, worker-pseudonym-
// bearing — per-row UEF-adjacent persistence remains the Admin's own later,
// separate step, untouched here) — this module never receives, computes,
// or stores a `pseudonym_id` or any worker-level identifier.
//
// PRIVACY: PII/forbidden-content scan (`lib/privacy/pii-guard.ts`) runs on
// every parsed row BEFORE any persistence; a rejection never reaches
// storage. The idempotency-claim `result` value is a small metadata summary
// only (batchId/rowCount/fileType) — never the raw file content or parsed
// rows (KORA-WP-011's own privacy discipline, `hashPayload()` stores only a
// hash, never the payload itself).

import { randomUUID, createHash } from 'crypto';
import { getSupabaseServiceClient } from '@/lib/supabase/server';
import { detectPiiInPayload, summarizePiiFindings } from '@/lib/privacy/pii-guard';
import { parseCsvContent } from '@/lib/data-intake/csv-parser';
import { parseExcelSheet } from '@/lib/data-intake/excel-parser';
import { executeIdempotent, hashPayload, type IdempotencyKey } from '@/lib/async-contract/idempotency-contract';
import { PostgresIdempotencyStore } from '@/lib/async-contract/postgres-idempotency-store';

export const INGEST_OPERATION = 'company_data_upload.ingest';

export const ALLOWED_INGEST_EXTENSIONS = ['csv', 'xlsx'] as const;
export type IngestFileExtension = (typeof ALLOWED_INGEST_EXTENSIONS)[number];

// R-1's own tested/decided bound (`105` §7) — never invented past it.
export const MAX_INGEST_ROWS = 100_000;
export const MAX_INGEST_BYTES = 25 * 1024 * 1024; // ~R-1's own 100K-row/23MB measurement, rounded up

const SOURCE_TYPE = 'company_self_service_ingest';

export interface CompanyIngestRequest {
  tenantId: string;
  actorId: string; // Company user id/email — audit attribution only, never a Worker identifier
  fileName: string;
  fileExtension: string;
  fileBuffer: Buffer;
  idempotencyKey?: string; // caller-supplied external correlation id (KORA-WP-011's own contract: "never generated by this module")
}

export interface CompanyIngestOutcome {
  kind: 'executed' | 'replayed' | 'replayed_failure' | 'conflict' | 'in_progress';
  batchId?: string;
  rowCount?: number;
  fileType?: string;
  error?: string;
}

export class CompanyIngestValidationError extends Error {}

function assertActor(tenantId: string, actorId: string): void {
  if (!tenantId || !actorId) {
    throw new Error('[KORA] company-ingest rejected: tenantId and actorId are required — this substrate never manufactures actor attribution.');
  }
}

async function logIngestAuditEvent(
  db: ReturnType<typeof getSupabaseServiceClient>,
  row: { tenantId: string; actorId: string; action: string; payload: Record<string, unknown> },
): Promise<void> {
  // Registry's own "Audit: ingestion attempt/failure events." Domain-owned
  // audit call — never routed through the generic idempotency contract's
  // own operational logger (KORA-WP-011's own explicit boundary, see its
  // JobOutcomeLogEntry doc comment).
  try {
    await db.schema('audit').from('audit_log').insert({
      tenant_id: row.tenantId,
      actor_role: 'COMPANY_ADMIN',
      actor_id: row.actorId,
      action: row.action,
      resource_type: 'analytics.source_batch',
      resource_id: null,
      payload: row.payload,
      ip_address: null,
    });
  } catch (e) {
    console.error('[company-ingest audit]', (e as Error).message);
  }
}

// Real, server-side parse — mirrors the admin accept route's own doctrine
// ("Reruns all validation server-side... NEVER trusts dry-run result from
// client"). This module re-parses from raw bytes; it never accepts a
// client-computed row count or preview as the write's own basis.
async function parseIngestFile(fileExtension: IngestFileExtension, fileBuffer: Buffer): Promise<{
  rows: Array<Record<string, string>>;
  headers: string[];
}> {
  if (fileExtension === 'csv') {
    const content = fileBuffer.toString('utf-8');
    const parsed = parseCsvContent(content);
    return { rows: parsed.rows, headers: parsed.headers };
  }
  // xlsx — first sheet only (matches this repo's own established
  // `data-submissions/[id]/files` precedent for a same-shape single-sheet
  // ingest read).
  const parsed = await parseExcelSheet(fileBuffer, '', MAX_INGEST_ROWS);
  return { rows: parsed.rows, headers: parsed.headers };
}

export async function ingestCompanyDataFile(req: CompanyIngestRequest): Promise<CompanyIngestOutcome> {
  assertActor(req.tenantId, req.actorId);

  const ext = req.fileExtension.toLowerCase();
  if (!ALLOWED_INGEST_EXTENSIONS.includes(ext as IngestFileExtension)) {
    throw new CompanyIngestValidationError(`Tipo file non supportato: .${ext}. Supportati: CSV, XLSX.`);
  }
  if (req.fileBuffer.byteLength > MAX_INGEST_BYTES) {
    throw new CompanyIngestValidationError(`File troppo grande. Limite: ${Math.round(MAX_INGEST_BYTES / 1024 / 1024)} MB.`);
  }
  if (req.fileBuffer.byteLength === 0) {
    throw new CompanyIngestValidationError('File vuoto.');
  }

  // Idempotency key: caller-supplied, or content-addressed by default so a
  // plain retry of the same file (no special client wiring required) is
  // still safely deduplicated (KORA-WP-011's own contract only forbids this
  // MODULE generating an opaque, non-reproducible key — a deterministic
  // content hash is a legitimate, reproducible "caller-supplied" choice
  // when literally no other correlation id is available).
  const contentHash = createHash('sha256').update(req.fileBuffer).digest('hex');
  const idempotencyKey = req.idempotencyKey && req.idempotencyKey.trim() !== ''
    ? req.idempotencyKey.trim()
    : `content:${contentHash}`;

  const key: IdempotencyKey = { tenantId: req.tenantId, operation: INGEST_OPERATION, key: idempotencyKey };
  const payload = { fileName: req.fileName, fileExtension: ext, contentHash };
  const store = new PostgresIdempotencyStore();
  const db = getSupabaseServiceClient();

  const outcome = await executeIdempotent<{ batchId: string; rowCount: number; fileType: string }>({
    store,
    key,
    payload,
    execute: async () => {
      const ext2 = ext as IngestFileExtension;
      const { rows } = await parseIngestFile(ext2, req.fileBuffer);

      if (rows.length > MAX_INGEST_ROWS) {
        throw new CompanyIngestValidationError(`Troppe righe nel file. Massimo ${MAX_INGEST_ROWS.toLocaleString('it-IT')} righe (limite validato da R-1).`);
      }

      const piiScan = detectPiiInPayload({ rows } as unknown as Record<string, unknown>);
      if (piiScan.hasPii) {
        const summary = summarizePiiFindings(piiScan.findings);
        await logIngestAuditEvent(db, {
          tenantId: req.tenantId, actorId: req.actorId, action: 'company_ingest_rejected_pii',
          payload: { fileName: req.fileName, piiSummary: summary },
        });
        throw new CompanyIngestValidationError('Il file contiene dati che potrebbero identificare individui. Rimuovere i dati personali prima di caricare.');
      }

      const batchId = randomUUID();
      const { error: insertErr } = await db
        .schema('analytics')
        .from('source_batch')
        .insert({
          id: batchId,
          tenant_id: req.tenantId,
          source_type: SOURCE_TYPE,
          source_name: `[Ingest] ${req.fileName}`,
          reporting_period: new Date().toISOString().slice(0, 7),
          row_count: rows.length,
          batch_status: 'ingested',
          payload_sample: { file_name: req.fileName, file_type: ext2, idempotency_key: idempotencyKey },
          created_by: req.actorId,
        });

      if (insertErr) {
        throw new Error(`Errore salvataggio ingestione: ${insertErr.message}`);
      }

      await logIngestAuditEvent(db, {
        tenantId: req.tenantId, actorId: req.actorId, action: 'company_ingest_succeeded',
        payload: { batchId, fileName: req.fileName, fileType: ext2, rowCount: rows.length },
      });

      return { batchId, rowCount: rows.length, fileType: ext2 };
    },
  });

  if (outcome.kind === 'executed' || outcome.kind === 'replayed') {
    return { kind: outcome.kind, batchId: outcome.result.batchId, rowCount: outcome.result.rowCount, fileType: outcome.result.fileType };
  }
  if (outcome.kind === 'replayed_failure') {
    return { kind: 'replayed_failure', error: outcome.error };
  }
  return { kind: outcome.kind };
}

// Exported for tests / callers that need the exact hash KORA-WP-011's
// contract will compute for a given payload (never recomputed differently
// by this module).
export { hashPayload };
